# Generated by Django 5.0 on 2024-08-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('Academic_specialization', models.CharField(choices=[('MA', 'Mobile Application'), ('WD', 'Web Development'), ('MAs', 'Maths')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='academics.teachers')),
            ],
        ),
    ]
