# Generated by Django 5.0 on 2024-08-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_courses_custom_id_teachers_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.FileField(blank=True, upload_to='static/images'),
        ),
    ]
