# Generated by Django 5.0 on 2024-08-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_teachers_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='Academic_specialization',
            new_name='academic_specialization',
        ),
    ]
