# Generated by Django 5.0 on 2024-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_teachers_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.FileField(blank=True, upload_to='assets/images'),
        ),
    ]
