# Generated by Django 5.0 on 2024-08-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_teachers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.FileField(blank=True, upload_to='static/image'),
        ),
    ]
