# Generated by Django 5.0 on 2024-08-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_teachers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.FileField(blank=True, upload_to='static/image'),
        ),
    ]
